apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-app
  labels:
    app: crud-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crud-app
  template:
    metadata:
      labels:
        app: crud-app
    spec:
      containers:
        - name: crud-app
          image: abhishekf5/ultimate-cicd:replaceImageTag
          ports:
            - containerPort: 8080